### ISSUE TITLE
Support for ASF's IPC GUI

### ISSUE THREAD

**Issue by azumukupoe** [clancy-chao/Steam-Bundle-Sites-Extension#10]
Is it posssible?

**Comment by clancy-chao** [comment]
It's possible.
I will need to do some research & testing before putting it on this script.
Maybe this weekend I can finish this.

**Comment by clancy-chao** [comment]
added ASF IPC in v2.10.0

**Comment by azumukupoe** [comment]
How do I enable it?

**Comment by azumukupoe** [comment]
Enabling the IPC breaks the script.

**Comment by clancy-chao** [comment]
Do you have more details? Like error messages from F12 console / what kind of broken behavours?

**Comment by azumukupoe** [comment]
The utility simply disappears. On latest version of Firefox Developer Edition.
Works without any issue on Chrome.

**Comment by clancy-chao** [comment]
[Firefox Websocket security issue](https://stackoverflow.com/questions/11768221/)

Firefox has a tighter policy on ws connection and throws an error when detected, therefore crashes the script.

Added error handling in v2.10.3, should be okay to use the script now.
Though can't help with the ASF log feature as each user needs to allow insecure connection on their browser.
