### ISSUE TITLE
Script not liking title with quotation marks (Humble)

### ISSUE THREAD

**Issue by DragRedSim** [clancy-chao/Steam-Bundle-Sites-Extension#11]
The recent (February 2019) Humble Monthly included a key for some DLC for an included game, titled "Rapture Rejects - Humble Exclusive "Safari Outfit" DLC". The script doesn't like the use of quotation marks in a title, as it reports the following JS error:
`Error: Syntax error, unrecognized expression: .heading-text[data-title="Rapture Rejects - Humble Exclusive "Safari Outfit" DLC"]`
After this, no further games are checked for ownership.
I'm guessing the fix involves checking the title for the quotation mark character, and escaping it, before passing it to the function. (Line 3530 seems to be where the search calculation is built.)

**Comment by clancy-chao** [comment]
Thank you for reporting this issue.
Fixed now.
