### ISSUE TITLE
Fanatical - either redeem box or game ownership, but not both

### ISSUE THREAD

**Issue by DragRedSim** [clancy-chao/Steam-Bundle-Sites-Extension#12]
If I open an order on Fanatical from a direct link, the ownership badges will show up, but not the box with options to redeem keys. However, if I access the order from the order list, the redemption box will appear, but there will be no icons for ownership or otherwise, and all will be treated as unowned.

**Comment by clancy-chao** [comment]
Thank you for reporting. Issue fixed.
