### ISSUE TITLE
STEAM好友动态页面变LAG

### ISSUE THREAD

**Issue by zelda0079** [clancy-chao/Steam-Bundle-Sites-Extension#16]
在https://steamcommunity.com/profiles/*/home/页面下观看好友动态
会因为STEAM WIDGET变LAG很吃电脑资源
TAMPERMONKEY运行SCRIPT数会变成很多
加入以下EXCLUDE之后没事
*store.steampowered.com/widget/*

我发现有些其他人做的SCRIPT也有这种情况

**Comment by zelda0079** [comment]
星号显示不到...

**Comment by clancy-chao** [comment]
已更新
