### ISSUE TITLE
建议整合Humble Key Restriction

### ISSUE THREAD

**Issue by FolStone** [clancy-chao/Steam-Bundle-Sites-Extension#24]
rt，与Humble Key Restriction这一必要插件有冲突，希望能至少避免冲突，或者增加全站的key锁区限制检测是最好不过了……

**Comment by FolStone** [comment]
啊貌似Humble Key Restriction那边的作者已经解决冲突问题了……当我没说好了

**Comment by clancy-chao** [comment]
腳本原本就有這功能
只是HB 更新後被擋住了點不開
已更新
