### ISSUE TITLE
Indiegala Latest UI

### ISSUE THREAD

**Issue by thom2804** [clancy-chao/Steam-Bundle-Sites-Extension#26]
So it looks like the UI of the indiegala site got updated today, altho thats nice, this script does not work anymore.
Could you please look into this and update the script?

**Comment by ReptilianWorldOrder** [comment]
I'm really hoping you'll be able to find a fix for the site too.

Indiegala is such a pain to use now :-/

**Comment by clancy-chao** [comment]
Script should now be working on Ingiegala.
