### ISSUE TITLE
Game info tooltip - can it be in English?

### ISSUE THREAD

**Issue by DragRedSim** [clancy-chao/Steam-Bundle-Sites-Extension#6]
When I hover over the owned/not owned icon on Humble download pages, a tooltip appears showing information about the game. However, it's all in Chinese. Is there a way to change that to English, or failing that, at least an option to turn off the tooltip popup?

**Comment by clancy-chao** [comment]
Thanks for reporting.
I will add a toggle to enable/disable this feature later the day.

**Comment by clancy-chao** [comment]
Added a toggle for this tooltips inside settings. It is also disabled by default for English users.

**Comment by AxJ11** [comment]
May I ask where to choose the language of the hovered tooltip?  Thanks!

**Comment by clancy-chao** [comment]
The tooltip is a feature provided by a Chinese Steam forum, no other language available.
I might do a translation sometime later.

**Comment by AxJ11** [comment]
Understood.  Thank you for the reply!  :)
