### ISSUE TITLE
(Issue with single site) Fanatical - multiple bundles in one order

### ISSUE THREAD

**Issue by DragRedSim** [clancy-chao/Steam-Bundle-Sites-Extension#7]
Hi again,
With Fanatical, it is possible to purchase multiple bundles in one transaction and results page. However, when doing so, the extension only reacts for the first bundle on the key page, not affecting the rest. This applies only to the modifications made, such as adding owned/not owned icons, as well as links to the Steam page of games.

The extension also treats any further games in the purchase in another bundle as unowned, therefore attempting to activate them, without checking first if they are owned. Additionally, even if "Ignore Owned" is selected, picking Redeem shows all codes, even those for already owned games.

**Comment by clancy-chao** [comment]
Thanks for reporting. I will fix this in the next couple days.

**Comment by clancy-chao** [comment]
Just updated to version 2.3.3 which should fix the multiple bundles purchased problem on Fanatical.

**Comment by DragRedSim** [comment]
Thanks for that, just tested with an order and it now acts on all bundles within an order. However, it still reveals keys for games that are already owned, even with "Ignore Owned" selected. It only adds games that are not owned to its list to activate, but I would prefer first activating games I don't own, before revealing all other games to add to my spreadsheet.

**Comment by clancy-chao** [comment]
@redion1992 
Thank you for reporting the issue, fixed it.
I have also remove the "Skip Owned" checkbox and replaced it with a select filter, this should be much more handy.

**Comment by DragRedSim** [comment]
This has started to occur again with the current version (2.12.4), only the first bundle is having owned/unowned status applied. All other games are treated as unowned.

**Comment by clancy-chao** [comment]
Which bundle did you have problem with?
Tried March bundle & Neptunia bundle and no problem with them.

**Comment by DragRedSim** [comment]
This is not the Humble issue with not reporting Steam app IDs, this is an older issue where Fanatical will only apply owned/unowned to the first bundle in a multi-bundle purchase.

**Comment by clancy-chao** [comment]
Ah right, sorry got it wrong.

Fixed now.
I don't have many multiple bundles orders to test, but there should not be no problem.
