### ISSUE TITLE
Join Keys w/ ASF Style is not outputting keys is ASF style

### ISSUE THREAD

**Issue by VladTheImpaller** [clancy-chao/Steam-Bundle-Sites-Extension#8]
Hello. 

Script does not output keys in format required by ASF.  I have `Join Keys w/ ASF Style ` enabled in settings and I also tried it in 2 different browsers to make sure I didn't mess anything up. 

From [ASF wiki](https://github.com/JustArchi/ArchiSteamFarm/wiki/Background-games-redeemer):  each line having a structure of `GameName\tcd-key\n`, where `\t` is tab character and `\n` is newline

SBSE currently outputs keys separated by comma and space sigh like so:

![image](https://user-images.githubusercontent.com/13596211/42255649-5d56970c-7f12-11e8-863c-615ce5b5aaf1.png)

This results in ASF not accepting current formatting: 

![image](https://user-images.githubusercontent.com/13596211/42255850-7b1d9a00-7f13-11e8-991f-969aa7d8c4b2.png)

I have a workaround where I can convert the output to needed format with Notepad++ using replace filter `,\s` to `\t` , but if this could be done with your script, that would be great!

**Comment by clancy-chao** [comment]
Hi there,

Didn't know ASF have this kind of feature, the `Join Keys w/ ASF Style` option is to output something like `!r XXXXX-XXXXX-XXXXX, ...`. The csv file you mentioned is for people that want to import keys to excel files.
I will add an option to output the `xxx.keys` file in the weekend.

**Comment by VladTheImpaller** [comment]
I wasn't talking about cvs specifically. I was expecting output to textarea have ASF formatting :)

**Comment by clancy-chao** [comment]
Updated to v2.5.0

I have modified the setting options a bit, enable ASF format option allows to output keys in `GameName\tcd-key\n` format and also add `!redeem` when join keys is checked.
The script also allows you export keys to `.keys` file.
